### ISSUE TITLE
Ubuntu: automated tests failing

### ISSUE THREAD

**Issue by jbencook** [mluerig/phenopype#6]
I'm having trouble getting the tests to run correctly on my Ubuntu 18.04 Desktop machine with an Anaconda Python 3.7 environment.

From the project's root directory, I run the following:

```
pip install tox
tox
```

After 3 tests pass, I get this:

```
measure pixel-to-mm-ratio
: cannot connect to X server
ERROR: InvocationError for command /home/jbencook/phenopype/.tox/py37/bin/pytest -s --cov=phenopype --cov-report=html (exited with code 1)
_______________________________________________________________________ summary _______________________________________________________________________
ERROR: py37: commands failed
```

**Comment by mluerig** [comment]
I have to check tomorrow on my other machine but it looks like xvfb is not installed on your system (on travis it is, that's why it passes there). xfvb is an X server to simulate a graphic environment, needed for some of the tests to run on CI. on your machine, you could try to install xvfb (e.g. https://stackoverflow.com/questions/21665914/installing-and-configuring-xvfb). I also included pytest-xvfb in the test deps, so that is called by tox. you could try to deactivate it, then the test GUI-windows should pop up (https://pypi.org/project/pytest-xvfb/)

**Comment by jbencook** [comment]
Nice - `apt-get install xvfb` took care of it! I'll add a couple suggestions to the [editor's template](https://github.com/pyOpenSci/software-review/issues/24#issuecomment-633104011) in the submission issue, but nothing is a dealbreaker for me and I'll close this issue.

**Comment by mluerig** [comment]
great! I will make a note to default testing without xvfb locally, but active on CI
